"""Minimal V2 production boundary exports."""

from .contracts import (
    CanonicalCandidate,
    EventDecisionRecord,
    EvidenceResult,
    EvidenceState,
    FetchedSource,
    RejectReason,
    ReportabilityEvidenceProvenance,
    ReportabilityReason,
    ReportabilityResult,
    ReportabilitySemanticCitation,
    ReportabilitySemanticMember,
    ReportabilitySemanticProposal,
    ReportabilitySemanticProposalProvider,
    ReportabilitySemanticRequest,
    ReportabilityStageFailure,
    ReportabilityState,
    ReportabilitySupportSpan,
    ScopeDiagnostic,
    ScopeResult,
    ScopeState,
    SourceDateFact,
    SourceDateKind,
    TemporalDiagnostic,
    TemporalResult,
)
from .evidence_service import EvidenceService
from .scope_classifier import (
    ScopeClassifier,
    ScopeSemanticRequest,
    ScopeSemanticResponse,
    ScopeSemanticSupport,
    ScopeSupportSpan,
)
from .temporal_rule import TemporalRule
from .taxonomy import (
    EXACT_TEXT_UNIQUE_RESOLUTION,
    EMTaxonomy,
    Taxonomy,
    TaxonomyOwner,
    TaxonomySemanticCitation,
    TaxonomySemanticMember,
    TaxonomySemanticProposal,
    TaxonomySemanticProposalProvider,
    TaxonomySemanticRequest,
    TaxonomyStageFailure,
)
from .report_workflow import ReportWorkflow, build_report_workflow

__all__ = [
    "CanonicalCandidate",
    "EvidenceResult",
    "EvidenceService",
    "EvidenceState",
    "FetchedSource",
    "RejectReason",
    "ReportabilityEvidenceProvenance",
    "ReportabilityReason",
    "ReportabilityResult",
    "ReportabilitySemanticCitation",
    "ReportabilitySemanticMember",
    "ReportabilitySemanticProposal",
    "ReportabilitySemanticProposalProvider",
    "ReportabilitySemanticRequest",
    "ReportabilityStageFailure",
    "ReportabilityState",
    "ReportabilitySupportSpan",
    "ScopeClassifier",
    "ScopeDiagnostic",
    "ScopeResult",
    "ScopeSemanticRequest",
    "ScopeSemanticResponse",
    "ScopeSemanticSupport",
    "ScopeState",
    "ScopeSupportSpan",
    "SourceDateFact",
    "SourceDateKind",
    "TemporalDiagnostic",
    "TemporalResult",
    "TemporalRule",
    "EXACT_TEXT_UNIQUE_RESOLUTION",
    "EMTaxonomy",
    "Taxonomy",
    "TaxonomyOwner",
    "TaxonomySemanticCitation",
    "TaxonomySemanticMember",
    "TaxonomySemanticProposal",
    "TaxonomySemanticProposalProvider",
    "ReportWorkflow",
    "build_report_workflow",
    "TaxonomySemanticRequest",
    "TaxonomyStageFailure",
]
